# Generated by Django 5.2.8 on 2025-12-21 18:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyIdentifierType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_type_id', models.IntegerField(unique=True)),
                ('identifier_type_code', models.CharField(max_length=30)),
                ('identifier_type_description', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=30)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.CharField(max_length=30)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartyRoleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type_id', models.IntegerField(unique=True)),
                ('role_type_code', models.CharField(max_length=30)),
                ('role_type_description', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=30)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.CharField(max_length=30)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('insurance_id', models.CharField(max_length=30, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_id', models.IntegerField(unique=True)),
                ('party_type', models.CharField(max_length=30)),
                ('display_name', models.CharField(max_length=100)),
                ('distinct_type', models.CharField(max_length=30)),
                ('distinct_value', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=30)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.CharField(max_length=30)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='PartyIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_id', models.IntegerField(unique=True)),
                ('identifier_value', models.CharField(max_length=30)),
                ('identifier_type_id', models.IntegerField(unique=True)),
                ('status', models.CharField(max_length=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=30)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.CharField(max_length=30)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('party_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.party')),
            ],
        ),
        migrations.CreateModel(
            name='PartyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField(unique=True)),
                ('role_type_id', models.IntegerField(unique=True)),
                ('status', models.CharField(max_length=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=30)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.CharField(max_length=30)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('party_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.party')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
