# Generated by Django 5.2.8 on 2025-12-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='partyidentifier',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='partyidentifiertype',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='partyrole',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='partyroletype',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
