# Generated by Django 5.2.8 on 2026-01-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_accounttype_account_accountbalance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionobligation',
            name='rf_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
