# Generated by Django 5.2.8 on 2026-01-02 15:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_transactionobligation_rf_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyRelationshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type_id', models.IntegerField(unique=True)),
                ('relationship_type_code', models.CharField(max_length=30)),
                ('relationship_type_description', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=30)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.CharField(max_length=30)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_id', models.IntegerField(unique=True)),
                ('relationship_type_id', models.IntegerField()),
                ('active_date_from', models.DateField()),
                ('active_date_to', models.DateField()),
                ('status', models.IntegerField(default=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=30)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.CharField(max_length=30)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('party_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.party')),
                ('relation_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='core.partyrole')),
                ('relation_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='core.partyrole')),
            ],
        ),
    ]
