# Generated by Django 5.2.8 on 2026-01-02 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_partyrelationshiptype_partyrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.accounttype'),
        ),
    ]
